version: "3.3"

services:
  db:
    image: postgres:15
    container_name: resmio-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  # resmio-feed-service:
  #   build: .
  #   container_name: resmio-feed-service
  #   restart: always
  #   depends_on:
  #     - db


volumes:
  pgdata: