name: Resmio Feed Service CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Linting & Tests
        run: pytest

      - name: Build Docker Image
        run: docker build -t resmio-feed-service .